import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Theming from '../../Theme/Theming'
import Footer from './Footer/page'
import Header from './Header/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theming>
        <Header />
        {children}
        <Footer />
        </Theming>
        </body>
    </html>
  )
}
